### ISSUE TITLE
Intermittent 500 error

### ISSUE THREAD

**Issue by davidmacp** [dadi/cloud#146]
Running automated tests and the the following is happening intermittently when trying to access /en/network

```
TypeError: this.stack[stackIdx] is not a function
    at err (/dadi/cloud/web/node_modules/@dadi/web/dadi/lib/api/index.js:222:29)
    at loadData (/dadi/cloud/web/node_modules/@dadi/web/dadi/lib/controller/index.js:236:14)
    at /dadi/cloud/web/node_modules/@dadi/web/dadi/lib/controller/index.js:454:7
    at /dadi/cloud/web/node_modules/async/lib/async.js:52:16
    at /dadi/cloud/web/node_modules/async/lib/async.js:1209:30
    at self.loadEventData (/dadi/cloud/web/node_modules/@dadi/web/dadi/lib/controller/index.js:447:11)
    at queue.then (/dadi/cloud/web/node_modules/@dadi/web/dadi/lib/controller/index.js:329:27)
    at 
```

**Comment by davidmacp** [comment]
Hasn't been seen for a while. Can be closed.
